name: Terraform Deployment

on:
  push:
    branches:
      - task-1  

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6  

      - name: Terraform Format Check
        run: terraform fmt -check

  # terraform-plan:
  #   runs-on: ubuntu-latest
  #   needs: terraform-check
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.9.6 

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Terraform Plan
  #       run: terraform plan

  # terraform-apply:
  #   runs-on: ubuntu-latest
  #   needs: terraform-plan
  #   if: github.ref == 'refs/heads/task-1'  
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.9.6 

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve
  #       env:
  #         TF_VAR_your_variable: ${{ secrets.YOUR_SECRET_VARIABLE }}  